stages:
  - build

.build:
  stage: build
  variables:
    REGISTRY_IMAGE: "${CI_REGISTRY_IMAGE}"
    DOCKERFILE: Dockerfile
    BUILD_CONTEXT_DIR: .
  tags:
    - k8s-root
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${REGISTRY_IMAGE}:${CI_COMMIT_SHA} -f ${DOCKERFILE} ${BUILD_CONTEXT_DIR}
    - docker push ${REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    - mkdir .images
    - echo "${REGISTRY_IMAGE}:${CI_COMMIT_SHA}" > .images/${CI_JOB_NAME}
  artifacts:
    paths:
      - .images/${CI_JOB_NAME}
  rules: &buildrules
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]/'

sunrise:
  extends: .build
  variables:
    REGISTRY_IMAGE: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}"
    DOCKERFILE: Dockerfile
